  server:
    port: 8081
  spring:
    rabbitmq:
      listener:
        simple:
          auto-startup: false
          acknowledge-mode: manual
          concurrency: 5
          prefetch: 10
      host: localhost
      port: 5672
      username: guest
      password: guest
    application:
      name: hmdp
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/dingping?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&characterEncoding=utf8
      username: root
      password: ${MYSQL_PASSWORD:123456}
    redis:
      host: 127.0.0.1
      port: 6379

      lettuce:
        pool:
          max-active: 30
          max-idle: 15
          min-idle: 5
          time-between-eviction-runs: 10s
    jackson:
      default-property-inclusion: non_null # JSON处理时忽略非空字段
  mybatis-plus:
    type-aliases-package: com.hmdp.entity # 别名扫描包
  logging:
    level:
      com.hmdp: debug

