---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by taozhu.
--- DateTime: 2026/10/2 11:53
---

-- KEYS[1] 桶的 key
-- ARGV[1] 桶容量 capacity
-- ARGV[2] 令牌补充速率（个/秒）
-- ARGV[3] 当前时间（毫秒）
-- ARGV[4] 本次请求需要的令牌数

local key        = KEYS[1]
local capacity   = tonumber(ARGV[1])
local rate       = tonumber(ARGV[2])
local now        = tonumber(ARGV[3])
local requested  = tonumber(ARGV[4])

--桶当前的状态 ：剩余令牌数 上次补充时间
local bucket = redis.call('hmget',key,'tokens','ts')
local tokens = tonumber(bucket[1])
local lastTs = tonumber(bucket[2])
-- 第一次访问，桶是满的
if tokens == nil then
    tokens = capacity
    lastTs = now
end

-- 惰性补充：按流逝的时间补令牌，但不超过桶容量
local delta = math.max(0, now - lastTs)
tokens = math.min(capacity, tokens + delta * rate / 1000)
-- 令牌够就扣，不够就拒
local allowed = tokens >= requested
if allowed then
    tokens = tokens - requested
end

-- 写回状态
redis.call('hmset', key, 'tokens', tokens, 'ts', now)
-- 桶空闲一段时间后自动过期，避免冷 key 常驻内存
redis.call('pexpire', key, math.ceil(capacity / rate * 1000) * 2)

if allowed then
    return 1
end
return 0